fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation

blog:
    resource: "@AppBundle/Controller/BlogController.php"
    type:     annotation

tag:
    resource: "@AppBundle/Controller/TagController.php"
    type:     annotation

widget:
    resource: "@AppBundle/Controller/WidgetController.php"
    type:     annotation

categorie:
    resource: "@AppBundle/Controller/CategorieController.php"
    type:     annotation

courrier:
    resource: "@AppBundle/Controller/CourrierController.php"
    type:     annotation

newsletter:
    resource: "@AppBundle/Controller/NewsletterController.php"
    type:     annotation


