blogroll:
    - { name: JeBosseEnGrandeDistribution, href: 'http://www.jebosseengrandedistribution.com/', title: JeBosseEnGrandeDistribution }
    - { name: Foodly, href: 'http://www.foodly.fr/', title: Foodly }
    - { name: 'Communication (Agro)alimentaire', href: 'http://www.communication-agroalimentaire.com/', title: 'Communication (Agro)alimentaire' }
    - { name: 'Cuisine Voozenoo', href: 'http://www.cuisine.voozenoo.fr/', title: 'Cuisine Voozenoo' }
    - { name: Marketing-PGC, href: 'http://www.marketing-pgc.com/', title: Marketing-PGC }
